### ISSUE TITLE
Project-WG roadmap

### ISSUE THREAD

**Issue by chuigda** [chuigda/Project-WG#9]
- [x] Launching the rocket!
- [x] OSF integration
- [x] Improvements on UI
- [x] Attachment API
- [x] Screen Animation API
- [x] Hand model rebuilding
- [x] VTS Integration
- [ ] <del>Legs & Foot modelling</del>
- [ ] <del>Arm model rebuilding</del>
- [x] Character redesign
- [ ] Neon character design modelling, texturing and shading
- [x] Modern OpenGL, Programmable pipeline
- [ ] Multithread rendering
- [x] Better material, texture and lighting

# Added in 10, April, 2023
- [ ] New, unified body animation API (BIS language)
- [ ] MediaPipe integration
